<!-- NavBar Start -->

<ul>
	<li><a href="http://localhost/GAMER/index.php">Home</a></li>
	<li class="lii"><header class="neonText animate__animated animate__fadeIn animate__delay-2s"> GamerFriend - The Ultimate Gameshop Finder</header></li>
	<li class="ri"><button class="button2 animate__animated animate__fadeIn animate__delay-2s" onclick="location.href='http://18.223.27.232/GAMER/login.php'">Login</button></li>
  <li class="ri"><button class="button2 animate__animated animate__fadeIn animate__delay-2s" onclick="location.href='http://18.223.27.232/GAMER/register.php'">Register</button></li>
	<li class="ri"><button class="button2 animate__animated animate__fadeIn animate__delay-2s" onclick="location.href='http://18.223.27.232/GAMER/submit_location.php'">Submit Location</button></li>
</ul>

<p></p> <!-- add this for add spacing -->