<!-- NavBar -->
<!-- Shows Home, Register and Login when Not Logged In-->

<ul>
	<li><a href="http://18.223.27.232/GAMER/index.php">Home</a></li>
	<li class="ri"><button class="button2 animate__animated animate__fadeIn animate__delay-2s" onclick="location.href='http://18.223.27.232/GAMER/login.php'">Login</button></li>
  	<li class="ri"><button class="button2 animate__animated animate__fadeIn animate__delay-2s" onclick="location.href='http://18.223.27.232/GAMER/register.php'">Register</button></li>
</ul>

<p></p>